# Generated by Django 4.1.1 on 2022-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customedetail_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customedetail',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
