# Generated by Django 4.1.1 on 2022-09-17 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_alter_customer_address_alter_customer_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeDetail',
            new_name='CustomerDetail',
        ),
    ]
