# Generated by Django 4.1.1 on 2022-09-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_customedetail_customerdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
    ]
