# Generated by Django 4.1.1 on 2022-09-17 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_customedetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeDetail',
            new_name='CustomerDetail',
        ),
    ]
